version: "3.9"
services:
  web:
    build: 
      context: .
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - REACT_APP_PORT=3000
      - REACT_APP_API_SCHEME=http
      - REACT_APP_API_ENDPOINT=api
      - REACT_APP_API_PORT=8000
    networks:
      - shared

volumes:
  mysql_volume:
  node_modules:

networks:
  shared:
    external: true
  
